sudo: false

language: csharp

# Ubuntu 14.04
dist: trusty

mono: none

dotnet: 2.1.302

env:
  global:
    - VIPS_VERSION=8.6.5
    - VIPS_TAR_VERSION=$VIPS_VERSION
    # - VIPS_WARNING=0
    - PATH=$HOME/vips/bin:$PATH
    - LD_LIBRARY_PATH=$HOME/vips/lib:$LD_LIBRARY_PATH
    - PKG_CONFIG_PATH=$HOME/vips/lib/pkgconfig:$PKG_CONFIG_PATH

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
  include:
    # these are just to make travis's UI a bit prettier
    - os: linux
    - os: osx
      # OS X 10.12
      osx_image: xcode9.2

cache:
  ccache: true
  directories:
    - $HOME/Library/Caches/Homebrew
    - tools
    - $HOME/vips

addons:
  apt:
    packages:
      - libexpat1-dev
      - gettext
      - liblcms2-dev
      - libmagickwand-dev
      - libopenexr-dev
      - libcfitsio3-dev
      - libfftw3-dev
      - libgif-dev
      - libgs-dev
      - libgsf-1-dev
      - libmatio-dev
      - libopenslide-dev
      - liborc-0.4-dev
      - libpango1.0-dev
      - libpoppler-glib-dev
      - librsvg2-dev
      - libwebp-dev
        # missing on trusty, unfortunately
        # - libwebpmux2
      - libglib2.0-dev

before_install: ./build/travis.sh

script: ./build.sh