image: Visual Studio 2017

# Version format
version: 1.0.4.{build}

init:
  - git config --global core.autocrlf true

# Environment
environment:
  VIPS_VERSION: "8.6.5"
  VIPS_ZIP_VERSION: "dev-w64-web-8.6.5"
  VIPS_WARNING: 0

# Build script
build_script:
  - ps: $env:VIPS_HOME = "C:\vips-dev-$env:VIPS_VERSION"
  - ps: $env:PATH = "$env:VIPS_HOME\bin;$env:PATH"
  - ps: .\build.ps1

# Do not build on tags (GitHub only)
skip_tags: true

pull_requests:
  do_not_increment_build_number: true

# Disable automatic tests and deployment
test: off
deploy: off

# Branches to build
branches:
  # Blacklist
  except:
    - gh-pages

# Build cache
cache:
- download -> appveyor.yml
- tools -> build.cake

artifacts:
  - path: '**\NetVips.*.nupkg' # find all NuGet packages recursively